version: '3.1'
services:
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ethicsdb
    ports:
    - "3306:3306"
  web:
    tty: true
    build: .
    environment:
      ADMIN_USER: admin
      ADMIN_MAIL: admin@ethics.de
      ADMIN_PASSWORD: admin
    command: bash -c "python3 manage.py migrate && python3 manage.py initadmin && python3 manage.py runserver 0.0.0.0:8080"
    ports:
    - "8080:8080"
    depends_on:
      - db