# Generated by Django 3.1.6 on 2021-02-12 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anwendung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=200)),
                ('anwendung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EthicAssessmentSoftware.anwendung')),
            ],
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=200)),
                ('schutzklasse', models.CharField(default='', max_length=25)),
                ('prioritaet', models.IntegerField(default=1)),
                ('ist_recht', models.BooleanField(default=False)),
                ('anwendung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EthicAssessmentSoftware.anwendung')),
            ],
        ),
        migrations.CreateModel(
            name='Konsequenz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=200)),
                ('bewertung', models.IntegerField()),
                ('betroffener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EthicAssessmentSoftware.stakeholder')),
                ('motivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EthicAssessmentSoftware.motivation')),
            ],
        ),
        migrations.CreateModel(
            name='Ansatz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=200)),
                ('auswirkung', models.IntegerField(default=0)),
                ('adressiert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EthicAssessmentSoftware.konsequenz')),
                ('anwendung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EthicAssessmentSoftware.anwendung')),
            ],
        ),
        migrations.CreateModel(
            name='Anforderung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True)),
                ('beschreibung', models.CharField(blank=True, default='', max_length=200)),
                ('ansatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EthicAssessmentSoftware.ansatz')),
            ],
        ),
    ]
