# Generated by Django 3.1.6 on 2021-02-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicAssessmentSoftware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansatz',
            name='auswirkung',
            field=models.IntegerField(default=0),
        ),
    ]
