# Generated by Django 3.1.6 on 2021-02-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EthicAssessmentSoftware', '0002_ansatz_auswirkung'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivation',
            old_name='shutzklasse',
            new_name='schutzklasse',
        ),
    ]
